### ISSUE TITLE
Wrong response content (probably) in case of HTTP_INTERNAL_SERVER

### ISSUE THREAD

**Issue by mlstoppa** [danlong005/RPGAPI#13]
When there is an error and the on error portion of code is triggered, the requester (browser or Postman) doesn't receive any response: they got stuck until a timeout occurs.
In my development, it happens when the on-error code is triggered in RPGAPI_start procedure.
The on-error block code is executed, the server starts listening for a new request, but the requester doesn't receive anything until its timeout is received.

**Comment by danlong005** [comment]
Ok. I think I have fixed this. I wasn't adding the newlines to the end of the response.

**Comment by danlong005** [comment]
Can you confirm that this is resolved?

**Comment by mlstoppa** [comment]
Not yet, sorry.
I'll try today.

**Comment by mlstoppa** [comment]
Yes, now it works. As for the tests I've done it always answer.
