### ISSUE TITLE
API documentation typo

### ISSUE THREAD

**Issue by mlstoppa** [danlong005/RPGAPI#14]
In API documentation there is a typo: 

> Headers 
> You can set response headers very easily. The following is an example.
> RPGAPI_getHeader(response : 'Connection' : 'close');

Should it be RPGAPI_setHeader instead?

**Comment by danlong005** [comment]
yep good catch! Thx.

**Comment by danlong005** [comment]
Fixed!
```Headers
You can set response headers very easily. The following is an example.

RPGAPI_setHeader(response : 'Connection' : 'close');```
