### ISSUE TITLE
Installation process ?

### ISSUE THREAD

**Issue by Chrisdeparis** [danlong005/RPGAPI#9]
Then make the following changes 63 -> 5B FC -> 5D 43 -> 7B DC -> 7D
Could you be more explicit ? I'll try to use your framework but i don't understand this step.

**Comment by danlong005** [comment]
@Chrisdeparis Once you run the command to create the conversion table it will popup... Once you do that you will see a hex code of 63 and it has a value in it... Put the value of 5B in it

I am working on a better solution for the translation right now so we dont have to do this step.

**Comment by danlong005** [comment]
@Chrisdeparis I have updated the README with a link to the SAVF that can be used to install the framework. This has everything you need to get started in it. This should resolve this issue. If it does please close this issue.
